### ISSUE TITLE
glassdoor crashes on start - java.lang.NumberFormatException: For input string: "0x100"

### ISSUE THREAD

**Issue by fschrofner** [fschrofner/glassdoor#4]
When trying to launch glassdoor, it immediately crashes with the following stack trace:

```
[ERROR] [07/01/2017 13:19:06.648] [default-akka.actor.default-dispatcher-2] [akka://default/user/$b] For input string: "0x100"
java.lang.NumberFormatException: For input string: "0x100"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.jline.utils.InfoCmp.parseInfoCmp(InfoCmp.java:555)
	at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:169)
	at org.jline.terminal.impl.PosixSysTerminal.<init>(PosixSysTerminal.java:43)
	at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:234)
	at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:149)
	at io.glassdoor.interface.CommandLineInterface.initialise(CommandLineInterface.scala:76)
	at io.glassdoor.interface.UserInterface$$anonfun$receive$1.applyOrElse(UserInterface.scala:40)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at io.glassdoor.interface.CommandLineInterface.aroundReceive(CommandLineInterface.scala:34)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
According to [this](https://stackoverflow.com/questions/44317384/sbt-error-failed-to-construct-terminal-falling-back-to-unsupported) stackoverflow question, it has something to do with ncurses.

Calling `export TERM=xterm-color` before launching glassdoor fixes the issue for me. Still it would be neat to fix it permanently.

**Comment by fschrofner** [comment]
Also occurs when you try to start the Scala REPL
![screenshot at 2017-07-28 15-00-17](https://user-images.githubusercontent.com/6865856/28718271-7dc8b692-73a5-11e7-9420-62e22a2e6a32.png)
